### ISSUE TITLE
Deploy on Heroku

### ISSUE THREAD

**Issue by cuongnguyengit** [nils-werner/pymushra#1]
Hi,

I'm trying to deploy pymushra on Heroku but no web process running.
I using Python App and "-e git+https://github.com/nils-werner/pymushra.git#egg=pymushra" in requirements file.
Webmushra was cloned in heroku github but i cant run web with command pymushra server.

Can you help me fixing my problem ?

Many thanks!

**Comment by nils-werner** [comment]
I have no experience with Heroku, and without an error message or anything I am not sure I can be of much help.
