### ISSUE TITLE
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'

### ISSUE THREAD

**Issue by IssacJay** [nils-werner/pymushra#5]
Whenever I try to download the results in any format I get a TypeError after send_file() is called from service.py. Any advice would be greatly appreciated!

 if as_attachment:
        return send_file(
            mem,
            attachment_filename="%s.%s" % (testid, filetype),
            as_attachment=True,
            cache_timeout=-1
        )

**Comment by nils-werner** [comment]
[The kwarg was changed in Flask 2.0](https://flask.palletsprojects.com/en/2.2.x/api/#flask.send_file). I have changed the dependency spec in `setup.py` to honor that.

In the meantime you can just downgrade Flask

```
pip install --upgrade flask<2.0
```
