### ISSUE TITLE
Incompatible when using Flask 2.x.x

### ISSUE THREAD

**Issue by senyuanfan** [nils-werner/pymushra#6]
Per this issue https://github.com/pallets/flask/issues/4753, the current webMushra fails when I tried to download results. 
It is probably due to the change in Flask 2.x.x, while pyMushra is still supporting Flask 1.x.x. I was able to fix the issue by changing  keyword arguments in `send_file()` in `pymushra/service.py`:
```
attachment_filename -> download_name
cache_timeout -> max_age
```

**Comment by nils-werner** [comment]
Thanks for letting me know!
